on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +59.55
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +60.55
	of handle_http_requests(...)
	| [192.168.0.8:45588] received 'GET /login'
on ln. 41, +60.86
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +61.87
	of handle_http_requests(...)
	| [192.168.0.8:45590] received 'GET /favic'
on ln. 41, +71.7
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +72.7
	of handle_http_requests(...)
	| [192.168.0.8:45598] received 'GET /login'
on ln. 41, +72.99
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +73.99
	of handle_http_requests(...)
	| [192.168.0.8:45600] received 'GET /favic'
on ln. 41, +118.08
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +119.09
	of handle_http_requests(...)
	| [192.168.0.8:45608] received 'GET / HTTP'
on ln. 50, +129.03
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +129.04
	of __del__(...)
	| garbage collecting SocketServer instance
