on ln. 29, +0.0
	of __init__(...)
	| bound successfully to :6969
on ln. 41, +3.78
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +4.78
	of handle_http_requests(...)
	| [192.168.0.8:45380] received 'GET /profi'
on ln. 41, +5.04
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +6.04
	of handle_http_requests(...)
	| [192.168.0.8:45382] received 'GET /favic'
on ln. 41, +11.85
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +12.86
	of handle_http_requests(...)
	| [192.168.0.8:45386] received 'POST /acti'
on ln. 41, +13.11
	of handle_connections(...)
	| received connection from 192.168.0.8
on ln. 178, +14.11
	of handle_http_requests(...)
	| [192.168.0.8:45388] received 'GET /favic'
on ln. 50, +18.28
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +18.3
	of __del__(...)
	| garbage collecting SocketServer instance
