on ln. 29, +0.0
	of __init__(...)
	| bound successfully to localhost:64873
on ln. 41, +10.47
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 170, +12.47
	of handle_http_requests(...)
	| [127.0.0.1:39258] received 'GET / HTTP'
on ln. 41, +12.67
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 170, +14.68
	of handle_http_requests(...)
	| [127.0.0.1:39262] received 'GET /favic'
on ln. 41, +26.32
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 170, +28.33
	of handle_http_requests(...)
	| [127.0.0.1:39266] received 'GET / HTTP'
on ln. 41, +28.53
	of handle_connections(...)
	| received connection from 127.0.0.1
on ln. 170, +30.53
	of handle_http_requests(...)
	| [127.0.0.1:39270] received 'GET /favic'
on ln. 50, +33.05
	of handle_connections(...)
	| user-interrupt caught
	| fatal error, exiting ...
on ln. 59, +33.07
	of __del__(...)
	| garbage collecting SocketServer instance
